### ISSUE TITLE
[BUG] Incorrect NSStringEncoding value 0x8000100 detected

### ISSUE THREAD

**Issue by john-mokaied** [AgoraIO-Community/VideoUIKit-Flutter#128]
**Describe the bug**
A log keep repeating as long as the user in video call by AgoraVideoViewer:
`Incorrect NSStringEncoding value 0x8000100 detected. Assuming NSASCIIStringEncoding. Will stop this compatibility mapping behavior in the near future.hen calling`
 
**To Reproduce**
Calling any screen contain
```
 AgoraVideoViewer(
                            enableHostControls: true,
                            client: videoController.client.value,
                            layoutType: Layout.floating,
)
```

**Expected behavior**
No logs about Incorrect NSStringEncoding value 0x8000100 detected..

**Screenshots**
<img width="896" alt="Screenshot 2023-03-15 at 21 18 27" src="https://user-images.githubusercontent.com/50097658/225433014-95f2ca8c-64cd-457d-a053-c61da1419e5f.png">
<img width="965" alt="Screenshot 2023-03-15 at 21 19 50" src="https://user-images.githubusercontent.com/50097658/225433034-55a9b028-7259-419b-8843-b1832a2fe0aa.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 14 Pro max - iPhone XS Max
 - OS: [e.g. iOS8.1] iOS 16.3
 
<img width="843" alt="Screenshot 2023-03-15 at 21 24 17" src="https://user-images.githubusercontent.com/50097658/225433995-0a624e1a-0100-49c4-8533-20dc32186cad.png">

 

**Additional context**
the logs stops when I close the video screen.

**Comment by yahyamokaied** [comment]
It's causing the video call to keep working even if I close the screen or restart the app.

**Comment by tadaspetra** [comment]
Yes, this log is coming from the `agora_rtc_engine` we're working with the team to remove that log from being printed. As far as I know the log output doesn't affect functionality. 

You mentioned the video keeps working if you close it or restart the app. That's not because of this log, it is because when you do those actions the `endCall` is not being called. If you close the app, the video call will end after some timeout. If you are hot reloading you might see multiple users. If you end up releasing this application, people of course won't be hot reloading so you won't have that problem in production.

**Comment by yahyamokaied** [comment]
> Yes, this log is coming from the `agora_rtc_engine` we're working with the team to remove that log from being printed. As far as I know the log output doesn't affect functionality.
> 
> You mentioned the video keeps working if you close it or restart the app. That's not because of this log, it is because when you do those actions the `endCall` is not being called. If you close the app, the video call will end after some timeout. If you are hot reloading you might see multiple users. If you end up releasing this application, people of course won't be hot reloading so you won't have that problem in production.
<img width="312" alt="Screenshot 2023-03-20 at 22 06 02" src="https://user-images.githubusercontent.com/50097658/226467299-a96e3d16-de3a-4337-b21a-5876b9f10fba.png">

Thank you for your response. Regarding ending the call, I am using "engine.leaveChannel()" and it appears that there are still multiple users 'local users' and the microphone is still working after rejoining the Video call. Is this the proper way to quit the call, or do you have any advice?

**Comment by tadaspetra** [comment]
Sorry for the late reply. I must have missed the notification. But with the `agora_uikit` you don't need to call the `.leaveChannel()` method, because that is all handled within the package. 

The `agora_rtc_engine` package make sure you call the `release()` method too, but it should not be possible to have multiple local users. Only possible if you didn't leave the channel properly, and then rejoined
